### ISSUE TITLE
Doesnt work at all?

### ISSUE THREAD

**Issue by wysisoft** [SrTobi/code-clip-ring#5]
![image](https://user-images.githubusercontent.com/15177964/33414632-cb627f62-d54f-11e7-9c9c-f7a947fd1cea.png)

whenever I click CTRL+C, i get this warn with these unicode characters?

**Comment by SrTobi** [comment]
Hmmm it currently works for me on Linux... are you using windows?

**Comment by wysisoft** [comment]
Yes windows

**Comment by evegreen** [comment]
i have "spawn xclip ENOENT" warning on linux, and found some strange thing: in doc you specify "clipreg.<cmd>", but in code i found only "clipring.<cmd>"

**Comment by SrTobi** [comment]
@wysisoft I got exactly the same error on windows. I apparently fixed it by updating the dependencies 😄 

I uploaded a .vsix that is the extension locally packed. Can you please download it, install it and test if it works for you? Then I would update the online package. [Here is the code-clip-ring-0.0.5.vsix](https://github.com/SrTobi/code-clip-ring/blob/packaged-0.0.5/code-clip-ring-0.0.5.vsix)

**Comment by SrTobi** [comment]
@evegreen do you have xclip installed? I fixed the readme... that was a typo

**Comment by wysisoft** [comment]
I'm still getting the error when installing from VSIX linked above. It says version 0.0.5 so I think it installed properly, but still getting the popup warning with the unicode garbage every time i click ctrl+shift+v. This is on windows 2012 with vscode 1.18.1

**Comment by evegreen** [comment]
@SrTobi no, i did not install it

**Comment by SrTobi** [comment]
@evegreen is it working after you installed it?

**Comment by evegreen** [comment]
@SrTobi I choose `Anjali.clipboard-history` plugin right now, cause i don't want to use any dependencies
